Node.js v25.3.0 [nodemon] app crashed - waiting for file changes before starting... [nodemon] restarting due to changes... [nodemon] starting `node index.js` Registered partial: footer Registered partial: head Registered partial: product/productCard node:events:486       throw er; // Unhandled 'error' event       ^
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1940:16)
    at listenInCluster (node:net:1997:12)
    at Server.listen (node:net:2102:7)
    at app.listen (C:\Users\TheHonoredOne\Desktop\xianfires-2.0.7-better-template\node_modules\express\lib\application.js:635:24)
    at bootstrap (file:///C:/Users/TheHonoredOne/Desktop/xianfires-2.0.7-better-template/index.js:99:13)
    at async file:///C:/Users/TheHonoredOne/Desktop/xianfires-2.0.7-better-template/index.js:107:1
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1976:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:89:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 3000
}

Node.js v25.3.0
[nodemon] app crashed - waiting for file changes before starting...